### ISSUE TITLE
使用 python 库遇到的问题（WIN10）

### ISSUE THREAD

**Issue by richardmyu** [richardmyu/Blog#19]
### 1.time

使用 `time` 模块时，误输 `time.strftime('%Y%m%D')`；

```python
# 正确写法
print('--%Y%m%d--', time.strftime('%Y%m%d'))
# --%Y%m%d-- 20210215

# 误写
print('--%Y%m%D--', time.strftime('%Y%m%D'))
# --%Y%m%D-- 20210202/15/21
```

在 [Python 参考手册.](https://docs.python.org/3/library/time.html#time.strftime)，可以用查到，没有明确指出 `%D`  的含义。暂时没弄明白，先记录一下这个结果。

**Comment by richardmyu** [comment]
### 2.cv2

这个库之前没有接触过，不过 demo 需要安装这个库，便就引入了这个库，然后安装这个库（pycharm 提示没有找到，按提示安装。。。）最后安装失败：

```
PackagesNotFoundError: The following packages are not available from current channels:

  - cv2

Current channels:

  - https://repo.anaconda.com/pkgs/main/win-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/win-64
  - https://repo.anaconda.com/pkgs/r/noarch
  - https://repo.anaconda.com/pkgs/msys2/win-64
  - https://repo.anaconda.com/pkgs/msys2/noarch
``` 

> 这里需要补充一句，pycharm 之前用的解释器是单独下载的 python 3.8，后来看到了anaconda，便安装了anaconda，并将 pycharm 的解释器更换为 anaconda3 下的 python 3.8。

**Comment by richardmyu** [comment]
### 3.anaconda

1. An HTTP error occurred when trying to retrieve this URL.

```shell
# wan
CondaHTTPError: HTTP 000 CONNECTION FAILED for url <https://repo.anaconda.com/pkgs/main/win-64/bottleneck-1.3.2-py37h2a96729_1.conda>
Elapsed: -

An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.
```

2. The current user does not have write permissions to the target environment.

```shell
EnvironmentNotWritableError: The current user does not have write permissions to the target environment.
  environment location: C:\xx\Anaconda3
```

**Comment by richardmyu** [comment]
> ### 2.cv2
> 这个库之前没有接触过，不过 demo 需要安装这个库，便就引入了这个库，然后安装这个库（pycharm 提示没有找到，按提示安装。。。）最后安装失败：
> 
> ```
> PackagesNotFoundError: The following packages are not available from current channels:
> 
>   - cv2
> 
> Current channels:
> 
>   - https://repo.anaconda.com/pkgs/main/win-64
>   - https://repo.anaconda.com/pkgs/main/noarch
>   - https://repo.anaconda.com/pkgs/r/win-64
>   - https://repo.anaconda.com/pkgs/r/noarch
>   - https://repo.anaconda.com/pkgs/msys2/win-64
>   - https://repo.anaconda.com/pkgs/msys2/noarch
> ```
> 
> ![](chrome-extension://cclaimiocmjpgihjgjhemeplmbinlaai/icons/copy.png)
> > 这里需要补充一句，pycharm 之前用的解释器是单独下载的 python 3.8，后来看到了anaconda，便安装了anaconda，并将 pycharm 的解释器更换为 anaconda3 下的 python 3.8。
> 
> 解决方法：这里面有一个隐藏问题，即安装库的名称应该是 `opencv-python`，而引入的时候要写出 `import cv2`，来源参考 [Py之cv2：cv2库(OpenCV，opencv-python)的简介、安装、使用方法(常见函数、方法等)最强详细攻略](https://blog.csdn.net/qq_41185868/article/details/79675875)
> 
> > 关于 opencv 和 cv2 名称问题，更多具体细节参考[Python · cv2（零）](https://zhuanlan.zhihu.com/p/24839371)。

**Comment by richardmyu** [comment]
特尔

**Comment by richardmyu** [comment]
### 4.pip

##### 4.1.`There was a problem confirming the ssl certificate`

```shell
python v3.8.8
pip v20.3.1

# pip.ini
[global]
index-url = https://pypi.tuna.tsinghua.edu.cn/simple/

[install]
trusted-host=pypi.tuna.tsinghua.edu.cn
```

使用 `pip install imageio` 时失败报错：

```
WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLError(1, '[SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1125)'))': /simple/imageio/
Could not fetch URL https://pypi.tuna.tsinghua.edu.cn/simple/imageio/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='pypi.tuna.tsinghua.edu.cn', port=443): Max retries exceeded with url: /simple/imageio/ (Caused by SSLError(SSLError(1, '[SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1125)'))) - skipping
ERROR: Could not find a version that satisfies the requirement imageio
ERROR: No matching distribution found for imageio
Could not fetch URL https://pypi.tuna.tsinghua.edu.cn/simple/pip/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='pypi.tuna.tsinghua.edu.cn', port=443): Max retries exceeded with url: /simple/pip/ (Caused by SSLError(SSLError(1, '[SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1125)'))) - skipping
```

查证后发现是代理的锅（【#5053】开了代理使得 `pip` 难以验证 SSL 证书，所以需要使用 `--trusted--host` 来指定可信任的安装源，但注意，这不是最安全的解决方法。没说其他解决方法，更没有提到安全解决方案，不过既然知道是代理的问题，不用想也知道关闭代理再安装是比较安全的方法）。

即：在开启了代理的情况下，需要添加 `--trusted-host pypi.xx.xx`；然而这条对清华源不管用，但对豆瓣源管用；要想使用清华源，可以选择暂时关闭代理。（只测试过清华和豆瓣的源，其他未测未知）

> 为了流畅的访问 github，而使用了代理；而代理本身除了这次影响，还影响到微软商店的访问和下载，再有的负面影响就是不开代理，正常网页都被影响，关闭“使用代理服务器”以后就好了。

```
https://pypi.douban.com/simple
https://pypi.tuna.tsinghua.edu.cn/simple/
```

---

[Could not fetch : There was a problem confirming the ssl certificate(SSL.c:3566) #5063](https://github.com/pypa/pip/issues/5063)

#### 4.2.`pip search`

在解决安装问题后，搜索也出了问题。搜索带来两种报错：

```
# 第一种
xmlrpc.client.Fault: <Fault -32500: "RuntimeError: PyPI's XMLRPC API is currently disabled due to unmanageable load and will be deprecated in the near future. See https://status.python.org/ for more information.">

# 第二种
ConnectionResetError: [WinError 10054] 远程主机强迫关闭了一个现有的连接。
...
pip._vendor.urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现 有的连接。', None, 10054, None))
```

第一个问题简单，看提示：由于无法管理的负载，PyPI 的 XMLRPC API 已被暂时禁用，并将在不久的将来弃用。

再看 [网站](https://status.python.org/)，简单说就是 `search` 功能被滥用，官方停了 :disappointed: :worried: :angry: :rage: :sleepy:。

第二种报错在第一种报错后再来一次，基于第一种报错的解析，可知知道访问频繁，被当成恶意访问，强制关闭了链接 :sob: :roll_eyes:。

---

[Remove the pip search command #5216](https://github.com/pypa/pip/issues/5216)

**Comment by richardmyu** [comment]
### 5.`python setup.py egg_info Check the logs for full command output`

```
Ubuntu 20.04.1
python 3.8.10
pip3 20.0.2
```

安装 `turtle` 时报错：

```shell
ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-kv40q4bf/turtle/setup.py'"'"'; __file__='"'"'/tmp/pip-install-kv40q4bf/turtle/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-kv40q4bf/turtle/pip-egg-info
         cwd: /tmp/pip-install-kv40q4bf/turtle/
    Complete output (6 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-kv40q4bf/turtle/setup.py", line 40
        except ValueError, ve:
                         ^
    SyntaxError: invalid syntax
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

语法不兼容的问题。`setup.py` 是 python2 语法，当前环境为 python3。

---

最后发现系统自带 `turtle`，故不用下载。

**Comment by richardmyu** [comment]
### 6.`No module named 'tkinter'`

调用系统安装的 `turtle` 的报错。

安装 `tk`:

```shell
sudo apt install python3-tk
```

---

参考：

[Python下"No module named _tkinter"问题解决过程总结](https://blog.csdn.net/blueheart20/article/details/78763208)
[Python3下提示No module named 'tkinter'＂问题解决](https://www.linuxidc.com/Linux/2019-04/158177.htm)

**Comment by richardmyu** [comment]
### 7.`skimage` & `matploylib`

**Comment by richardmyu** [comment]
### 7.引入包错误

- `cannot import name 'escape' from 'jinja2'`

> 参考：[[Solved] ImportError: cannot import name 'escape' from 'jinja2'](https://namespaceit.com/blog/importerror-cannot-import-name-escape-from-jinja2)

具体：

```shell
$ py app.py                      
Traceback (most recent call last):
  File "app.py", line 3, in <module>
    from flask import Flask, render_template, url_for, request, redirect
  File "/home/.../todo_app/venv/lib/python3.8/site-packages/flask/__init__.py", line 14, in <module>
    from jinja2 import escape
ImportError: cannot import name 'escape' from 'jinja2' (/home/.../todo_app/venv/lib/python3.8/site-packages/jinja2/__init__.py)
(venv) 
```

分析：

jinja 升级版本移除了这个函数。

方案：

1.降级：`jinja2<3.1.0`；
2.换包：`from markupsafe import escape` (`jinja` 中的 `Markup` 和 `escape` 应该 `Markusafe` 引入)；

---

- `cannot import name ‘json’ from itsdangerous`

> 参考：[[Solved] ImportError: cannot import name ‘json’ from itsdangerous](https://itsmycode.com/importerror-cannot-import-name-json-from-itsdangerous/)

具体：

```shell
$ py app.py                      
Traceback (most recent call last):
  File "app.py", line 3, in <module>
    from flask import Flask, render_template, url_for, request, redirect
  File "/home/.../todo_app/venv/lib/python3.8/site-packages/flask/__init__.py", line 19, in <module>
    from . import json
  File "/home/.../todo_app/venv/lib/python3.8/site-packages/flask/json/__init__.py", line 15, in <module>
    from itsdangerous import json as _json
ImportError: cannot import name 'json' from 'itsdangerous' (/home/.../todo_app/venv/lib/python3.8/site-packages/itsdangerous/__init__.py)
(venv) 
```

分析：还是版本问题

方案：解决这个问题后，又出现了其他引入问题，索性将版本都升级到最新版本，成功运行。

**Comment by qixingyu-code** [comment]
你好，请问你遇到过如下错误吗？
在使用conda 命令安装package的时候，提示conda的版本过低，使用conda uodate conda 命令，但是出现问题
Solving environment: failed
InvalidVersionSpecError: Invalid version spec: =2.7
我应该如何顺利更新自己的conda 呢

**Comment by Lr-2002** [comment]
@qixingyu-code 同问，请问朋友你解决了这个问题不
